title: 'page - project'
template: pages/project
layout: layout
revisions: false
route: /project
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
