title: projects
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        import: project
      -
        handle: article_content
        field:
          collapse: false
          always_show_set_button: false
          previews: true
          sets:
            video:
              display: Video
              fields:
                -
                  handle: video_title
                  field:
                    input_type: text
                    antlers: false
                    display: 'Video Title'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
                -
                  handle: video_description
                  field:
                    antlers: false
                    display: 'Video Description'
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
                -
                  handle: video_link
                  field:
                    display: 'Video Link'
                    type: video
                    icon: video
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
            images:
              display: Images
              fields:
                -
                  handle: images_title
                  field:
                    input_type: text
                    antlers: false
                    display: 'Images Title'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
                -
                  handle: images_description
                  field:
                    antlers: false
                    display: 'Images Description'
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
                -
                  handle: images
                  field:
                    mode: list
                    container: assets
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    display: Images
                    type: assets
                    icon: assets
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: 'Article content'
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: sidebar_content
        field:
          fields:
            -
              handle: sidebar_module_title
              field:
                input_type: text
                antlers: false
                display: 'Sidebar Module Title'
                type: text
                icon: text
                listable: hidden
                instructions_position: above
                visibility: visible
                always_save: false
            -
              handle: sidebar_module_content
              field:
                antlers: false
                display: 'Sidebar Module Content'
                type: textarea
                icon: textarea
                listable: hidden
                instructions_position: above
                visibility: visible
                always_save: false
          mode: table
          add_row: 'Ajouter un module'
          reorderable: true
          display: 'Sidebar Content'
          type: grid
          icon: grid
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
